executor: CeleryExecutor
airflow:
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
workers:
  replicas: 3
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/carstenm63/airflow-dags-repo.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    subPath: ""

